- hosts:
    - all
  remote_user: raspc
  become: yes

  vars:
    ansible_port: 2225
    rasp_open_firewall_port :
     - "{{ ansible_port }}"
     - 22

  tasks:
    - name: Active Firewall.
      ufw:
        state: enabled
        policy: deny
      when: rasp_open_firewall_port

    - name: Open port.
      ufw:
        rule: allow
        port: '{{ item }}'
      with_items: "{{ rasp_open_firewall_port }}"
      when: rasp_open_firewall_port
